//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hosteria.Front.ServicioUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntradaUsuarioTraer", Namespace="http://schemas.datacontract.org/2004/07/Hosteria.Clases.Entrada")]
    [System.SerializableAttribute()]
    public partial class EntradaUsuarioTraer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutUsuario {
            get {
                return this.RutUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.RutUsuarioField, value) != true)) {
                    this.RutUsuarioField = value;
                    this.RaisePropertyChanged("RutUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaUsuarioTraer", Namespace="http://schemas.datacontract.org/2004/07/Hosteria.Clases.Respuesta")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Hosteria.Front.ServicioUsuario.MotivoNoExitoTraerUsusario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Hosteria.Front.ServicioUsuario.EntradaUsuarioTraer))]
    public partial class RespuestaUsuarioTraer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Hosteria.Front.ServicioUsuario.MotivoNoExitoTraerUsusario MotivoNoExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Hosteria.Front.ServicioUsuario.MotivoNoExitoTraerUsusario MotivoNoExito {
            get {
                return this.MotivoNoExitoField;
            }
            set {
                if ((this.MotivoNoExitoField.Equals(value) != true)) {
                    this.MotivoNoExitoField = value;
                    this.RaisePropertyChanged("MotivoNoExito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MotivoNoExitoTraerUsusario", Namespace="http://schemas.datacontract.org/2004/07/Hosteria.Clases.Respuesta")]
    public enum MotivoNoExitoTraerUsusario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorNoControlado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsuarioNoExiste = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IServicioUsuario")]
    public interface IServicioUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/TraerUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/TraerUsuarioResponse")]
        Hosteria.Front.ServicioUsuario.RespuestaUsuarioTraer TraerUsuario(Hosteria.Front.ServicioUsuario.EntradaUsuarioTraer entradaUsuarioTraer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/TraerUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/TraerUsuarioResponse")]
        System.Threading.Tasks.Task<Hosteria.Front.ServicioUsuario.RespuestaUsuarioTraer> TraerUsuarioAsync(Hosteria.Front.ServicioUsuario.EntradaUsuarioTraer entradaUsuarioTraer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioChannel : Hosteria.Front.ServicioUsuario.IServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<Hosteria.Front.ServicioUsuario.IServicioUsuario>, Hosteria.Front.ServicioUsuario.IServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hosteria.Front.ServicioUsuario.RespuestaUsuarioTraer TraerUsuario(Hosteria.Front.ServicioUsuario.EntradaUsuarioTraer entradaUsuarioTraer) {
            return base.Channel.TraerUsuario(entradaUsuarioTraer);
        }
        
        public System.Threading.Tasks.Task<Hosteria.Front.ServicioUsuario.RespuestaUsuarioTraer> TraerUsuarioAsync(Hosteria.Front.ServicioUsuario.EntradaUsuarioTraer entradaUsuarioTraer) {
            return base.Channel.TraerUsuarioAsync(entradaUsuarioTraer);
        }
    }
}
