//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hosteria.Front.ServicioUsuario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuario.IServicioUsuario")]
    public interface IServicioUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/TraerUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/TraerUsuarioResponse")]
        Hosteria.Front.ServicioUsuario.Respuesta TraerUsuario(Hosteria.Front.ServicioUsuario.Entrada request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUsuario/TraerUsuario", ReplyAction="http://tempuri.org/IServicioUsuario/TraerUsuarioResponse")]
        System.Threading.Tasks.Task<Hosteria.Front.ServicioUsuario.Respuesta> TraerUsuarioAsync(Hosteria.Front.ServicioUsuario.Entrada request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Entrada", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Entrada {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Datos;
        
        public Entrada() {
        }
        
        public Entrada(string Datos) {
            this.Datos = Datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Respuesta", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Respuesta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Exito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public short MotivoNoExito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Datos;
        
        public Respuesta() {
        }
        
        public Respuesta(bool Exito, short MotivoNoExito, string Datos) {
            this.Exito = Exito;
            this.MotivoNoExito = MotivoNoExito;
            this.Datos = Datos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUsuarioChannel : Hosteria.Front.ServicioUsuario.IServicioUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUsuarioClient : System.ServiceModel.ClientBase<Hosteria.Front.ServicioUsuario.IServicioUsuario>, Hosteria.Front.ServicioUsuario.IServicioUsuario {
        
        public ServicioUsuarioClient() {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hosteria.Front.ServicioUsuario.Respuesta Hosteria.Front.ServicioUsuario.IServicioUsuario.TraerUsuario(Hosteria.Front.ServicioUsuario.Entrada request) {
            return base.Channel.TraerUsuario(request);
        }
        
        public bool TraerUsuario(ref string Datos, out short MotivoNoExito) {
            Hosteria.Front.ServicioUsuario.Entrada inValue = new Hosteria.Front.ServicioUsuario.Entrada();
            inValue.Datos = Datos;
            Hosteria.Front.ServicioUsuario.Respuesta retVal = ((Hosteria.Front.ServicioUsuario.IServicioUsuario)(this)).TraerUsuario(inValue);
            MotivoNoExito = retVal.MotivoNoExito;
            Datos = retVal.Datos;
            return retVal.Exito;
        }
        
        public System.Threading.Tasks.Task<Hosteria.Front.ServicioUsuario.Respuesta> TraerUsuarioAsync(Hosteria.Front.ServicioUsuario.Entrada request) {
            return base.Channel.TraerUsuarioAsync(request);
        }
    }
}
