//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hosteria.Front.Negocio.ServiciosEmpresa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiciosEmpresa.IServicioEmpresa")]
    public interface IServicioEmpresa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/CrearEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/CrearEmpresaResponse")]
        Hosteria.Clases.Respuesta.RespuestaEmpresaCrear CrearEmpresa(Hosteria.Clases.Entrada.EntradaEmpresaCrear entradaEmpresaCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/CrearEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/CrearEmpresaResponse")]
        System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresaCrear> CrearEmpresaAsync(Hosteria.Clases.Entrada.EntradaEmpresaCrear entradaEmpresaCrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/ModificarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/ModificarEmpresaResponse")]
        Hosteria.Clases.Respuesta.RespuestaEmpresaModificar ModificarEmpresa(Hosteria.Clases.Entrada.EntradaEmpresaModificar entradaEmpresaModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/ModificarEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/ModificarEmpresaResponse")]
        System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresaModificar> ModificarEmpresaAsync(Hosteria.Clases.Entrada.EntradaEmpresaModificar entradaEmpresaModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/ListarEmpresas", ReplyAction="http://tempuri.org/IServicioEmpresa/ListarEmpresasResponse")]
        Hosteria.Clases.Respuesta.RespuestaEmpresasListar ListarEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/ListarEmpresas", ReplyAction="http://tempuri.org/IServicioEmpresa/ListarEmpresasResponse")]
        System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresasListar> ListarEmpresasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/TraerEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/TraerEmpresaResponse")]
        Hosteria.Clases.Respuesta.RespuestaEmpresasTraer TraerEmpresa(int idEmpresa, string rutEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEmpresa/TraerEmpresa", ReplyAction="http://tempuri.org/IServicioEmpresa/TraerEmpresaResponse")]
        System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresasTraer> TraerEmpresaAsync(int idEmpresa, string rutEmpresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEmpresaChannel : Hosteria.Front.Negocio.ServiciosEmpresa.IServicioEmpresa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEmpresaClient : System.ServiceModel.ClientBase<Hosteria.Front.Negocio.ServiciosEmpresa.IServicioEmpresa>, Hosteria.Front.Negocio.ServiciosEmpresa.IServicioEmpresa {
        
        public ServicioEmpresaClient() {
        }
        
        public ServicioEmpresaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEmpresaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpresaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hosteria.Clases.Respuesta.RespuestaEmpresaCrear CrearEmpresa(Hosteria.Clases.Entrada.EntradaEmpresaCrear entradaEmpresaCrear) {
            return base.Channel.CrearEmpresa(entradaEmpresaCrear);
        }
        
        public System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresaCrear> CrearEmpresaAsync(Hosteria.Clases.Entrada.EntradaEmpresaCrear entradaEmpresaCrear) {
            return base.Channel.CrearEmpresaAsync(entradaEmpresaCrear);
        }
        
        public Hosteria.Clases.Respuesta.RespuestaEmpresaModificar ModificarEmpresa(Hosteria.Clases.Entrada.EntradaEmpresaModificar entradaEmpresaModificar) {
            return base.Channel.ModificarEmpresa(entradaEmpresaModificar);
        }
        
        public System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresaModificar> ModificarEmpresaAsync(Hosteria.Clases.Entrada.EntradaEmpresaModificar entradaEmpresaModificar) {
            return base.Channel.ModificarEmpresaAsync(entradaEmpresaModificar);
        }
        
        public Hosteria.Clases.Respuesta.RespuestaEmpresasListar ListarEmpresas() {
            return base.Channel.ListarEmpresas();
        }
        
        public System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresasListar> ListarEmpresasAsync() {
            return base.Channel.ListarEmpresasAsync();
        }
        
        public Hosteria.Clases.Respuesta.RespuestaEmpresasTraer TraerEmpresa(int idEmpresa, string rutEmpresa) {
            return base.Channel.TraerEmpresa(idEmpresa, rutEmpresa);
        }
        
        public System.Threading.Tasks.Task<Hosteria.Clases.Respuesta.RespuestaEmpresasTraer> TraerEmpresaAsync(int idEmpresa, string rutEmpresa) {
            return base.Channel.TraerEmpresaAsync(idEmpresa, rutEmpresa);
        }
    }
}
